[package]
name = "final_proj"
version = "0.1.0"
authors = ["matriley"]

[dependencies]
glutin = "*"
gl = "0.6.0"
cgmath = "0.16.1"
hound = "1.0.0"
num = "0.1.40"
rustfft = "2.0.0"
find_folder = "0.3"
portaudio = "0.7"
sample = "0.10.0"
